export const timeWindowToNumber: { [key: string]: number } = {
	'24H': 0,
	'1W': 1,
	'1M': 2,
	'3M': 3,
	'1Y': 4,
};

export const assets = [
	'bitcoin',
	'ethereum',
	'binancecoin',
	'avalanche-2',
	'solana',
	'chainlink',
	'algorand',
	'matic-network',
	'tether',
	'usd-coin',
];

export const symbolToCoingeckoId: { [key: string]: string } = {
	btc: 'bitcoin',
	eth: 'ethereum',
	bnb: 'binancecoin',
	sol: 'solana',
	usdt: 'tether',
	usdc: 'usd-coin',
	xrp: 'ripple',
	dogecoin: 'dogecoin',
	ada: 'cardano',
	dot: 'polkadot',
	dai: 'dai',
	trx: 'tron',
	avax: 'avalanche-2',
	matic: 'matic-network',
	link: 'chainlink',
	algo: 'algorand',
	atom: 'cosmos',
	usd: 'usd',
};

export const assetToImage: { [key: string]: string } = {
	btc: 'https://cryptologos.cc/logos/bitcoin-btc-logo.svg?v=022',
	eth: 'https://cryptologos.cc/logos/ethereum-eth-logo.svg?v=022',
	bnb: 'https://cryptologos.cc/logos/bnb-bnb-logo.svg?v=022',
	sol: 'https://cryptologos.cc/logos/solana-sol-logo.svg?v=022',
	avax: 'https://cryptologos.cc/logos/avalanche-avax-logo.svg?v=022',
	dot: 'https://cryptologos.cc/logos/polkadot-new-dot-logo.svg?v=022',
	matic: 'https://cryptologos.cc/logos/polygon-matic-logo.svg?v=022',
	link: 'https://cryptologos.cc/logos/chainlink-link-logo.svg?v=022',
	atom: 'https://cryptologos.cc/logos/cosmos-atom-logo.svg?v=022',
	// algo: 'https://cryptologos.cc/logos/algorand-algo-logo.svg?v=022',
	usdt: 'https://cryptologos.cc/logos/tether-usdt-logo.svg?v=022',
	usdc: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.svg?v=022',
	ada: 'https://cryptologos.cc/logos/cardano-ada-logo.svg?v=022',
	doge: 'https://cryptologos.cc/logos/dogecoin-doge-logo.svg?v=022',
	// near: 'https://cryptologos.cc/logos/near-protocol-near-logo.svg?v=022',
	uni: 'https://cryptologos.cc/logos/uniswap-uni-logo.svg?v=022',
	trx: 'https://cryptologos.cc/logos/tron-trx-logo.svg?v=022',
	ftm: 'https://cryptologos.cc/logos/fantom-ftm-logo.svg?v=022',
	icp: 'https://cryptologos.cc/logos/internet-computer-icp-logo.svg?v=022',
	xmr: 'https://cryptologos.cc/logos/monero-xmr-logo.svg?v=022',
	aave: 'https://cryptologos.cc/logos/aave-aave-logo.svg?v=022',
	dai: 'https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.svg?v=022',
	busd: 'https://cryptologos.cc/logos/binance-usd-busd-logo.svg?v=022',
	ltc: 'https://cryptologos.cc/logos/litecoin-ltc-logo.svg?v=022',
	ftt: 'https://cryptologos.cc/logos/ftx-token-ftt-logo.svg?v=022',
	etc: 'https://cryptologos.cc/logos/ethereum-classic-etc-logo.svg?v=022',
	fil: 'https://cryptologos.cc/logos/filecoin-fil-logo.svg?v=022',
	stx: 'https://cryptologos.cc/logos/stacks-stx-logo.svg?v=022',
	mkr: 'https://cryptologos.cc/logos/maker-mkr-logo.svg?v=022',
	cake: 'https://cryptologos.cc/logos/pancakeswap-cake-logo.svg?v=022',
	zec: 'https://cryptologos.cc/logos/zcash-zec-logo.svg?v=022',
	crv: 'https://cryptologos.cc/logos/curve-dao-token-crv-logo.svg?v=022',
	amp: 'https://cryptologos.cc/logos/amp-amp-logo.svg?v=022',
	'1inch': 'https://cryptologos.cc/logos/1inch-1inch-logo.svg?v=022',
	snx: 'https://cryptologos.cc/logos/synthetix-network-token-snx-logo.svg?v=022',
	sushi: 'https://cryptologos.cc/logos/sushiswap-sushi-logo.svg?v=022',
	kda: 'https://cryptologos.cc/logos/kadena-kda-logo.svg?v=022',
	yfi: 'https://cryptologos.cc/logos/yearn-finance-yfi-logo.svg?v=022',
	comp: 'https://cryptologos.cc/logos/compound-comp-logo.svg?v=022',
	ankr: 'https://cryptologos.cc/logos/ankr-ankr-logo.svg?v=022',
	ens: 'https://cryptologos.cc/logos/ethereum-name-service-ens-logo.svg?v=022',
	srm: 'https://cryptologos.cc/logos/serum-srm-logo.svg?v=022',
	shib: 'https://cryptologos.cc/logos/shiba-inu-shib-logo.svg?v=022',
	mana: 'https://cryptologos.cc/logos/decentraland-mana-logo.svg?v=022',
	leo: 'https://cryptologos.cc/logos/unus-sed-leo-leo-logo.svg?v=022',
	vet: 'https://cryptologos.cc/logos/vechain-vet-logo.svg?v=022',
};
